disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "lwd3c's Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "29 June 2004"
logo = "hacker.png"
secondaryLogo = "cscv.jpg"
description = "Hello bro !"
copyright = ""

  [params.author]
  links = [ ]

["params.author"]
name = "lwd3c"
email = "leduc290604@gmail.com"
imageQuality = "100"
headline = "CTF player | Pwner"
bio = "Binary Exploitation"
image = "ducc.jpg"
