[[main]]
none = "none"

[[main]]
name = "Home"
pageRef = "/"
identifier = "dqwshK7YIo"
weight = 1

[[main]]
name = "Categories"
pageRef = "categories"
identifier = "roE4t09YhG"
weight = 2

[[main]]
name = "About"
pageRef = "about"
identifier = "U86Y1duw5F"
weight = 9_999

[[footer]]
none = "none"
