[[main]]
none = "none"

[[main]]
name = "Home"
pageRef = "/"
identifier = "dqwshK7YIo"
weight = 1

[[main]]
name = "Articles"
pageRef = "/articles"
identifier = "Rscpg43Q6Y"
weight = 2

[[main]]
name = "Categories"
pageRef = "/categories"
identifier = "JcKA7dLkN2"
weight = 9_999

[[footer]]
none = "none"
