colorScheme = "forest"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = false
replyByEmail = false
mainSections = [ "posts" ]
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
firebase = { }
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }
enableStyledScrollbar = true
highlightCurrentMenuArea = true
disableImageZoom = true
smartTOC = true
smartTOCHideUnfocusedChildren = true
showViews = true
showLikes = true
defaultBackgroundImage = "coffe.gif"
defaultFeaturedImage = "tn.png"
defaultSocialImage = "msec.ico"

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "coffe.gif"
showRecent = true
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts/"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false
disableHeroImageFilter = true

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showHero = true
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = false
showWordCount = true
showZenMode = true
showAuthorBottom = false
heroStyle = "background"
showRelatedContent = true
showComments = false
externalLinkForceNewTab = true
relatedContentLimit = "3"

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false
heroStyle = "background,"
showImage = true

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
cardView = true
heroStyle = "background"
series = "series"
seriesOpened = true

[term]
showHero = true
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = true
cardView = false
cardViewScreenWidth = false
heroStyle = "background"

[author]
name = "lwd3c"
image = "img/avatar.jpg"
headline = "CTF player | Pwner"
bio = "Binary Exploitation."
